---

# This is a basic workflow to help you get started with Actions

name: FortiDevSec Scanner CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: SAST
        run: |
          docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
          docker run --rm --mount type=bind,source=$PWD,target=/scan registry.fortidevsec.forticloud.com/fdevsec_sast:latest
          env | grep -E "GITHUB_ACTIONS|GITHUB_RUN_NUMBER|GITHUB_REF_NAME|GITHUB_SHA" > /tmp/env
          

jobs:
  build:
   runs-on: self-hosted
   steps:
   - uses: actions/checkout@v2
   - name: DAST_PROXY_SERVER
     run: |
        export EMAIL=dgooch@fortinet.com LICENSE_SERIAL=FFPENT0000232040 ASSET_TOKEN=VVm8YERC8EPQAeT1bqlO18wTXA5EtSlls4+/pitgbMdc1infuOHqKgMxeKDrt/8OHKnQsfC4dB5RloiWSDRO8Lp8MzMA8Gu2jA3jAA== SCANURL=https://www.choogyddad.com SCANTYPE=1 ASSET=bc938243-3597-4792-bf67-09e2acc4051a
        env | grep -E "EMAIL|LICENSE_SERIAL|ASSET_TOKEN|SCANURL|SCANTYPE|ASSET" > /tmp/env
        docker pull registry.fortidast.forticloud.com/dastdevopsproxy:latest
        docker run --rm --env-file /tmp/env --network=host registry.fortidast.forticloud.com/dastdevopsproxy:latest
